# Generated by Django 4.1.1 on 2023-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_training_likedexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
