# Generated by Django 4.1.1 on 2023-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_exercise_reps_exercise_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='training',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
